<?xml version="1.0"?>
<package format="3">
  <name>limo_bringup</name>
  <version>0.0.0</version>
  <description>LIMO bringup package for ROS 2 Jazzy</description>

  <maintainer email="you@example.com">atwork</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>rclpy</depend>

  <depend>limo_base</depend>
  <depend>limo_msgs</depend>
  <depend>limo_description</depend>

  <depend>urg_node</depend>
  <depend>tf2_ros</depend>
  <depend>rviz2</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

